name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        wagtail-version: ['2.15', '2.16', '3.0', 'main']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install .

      - name: Install Wagtail package
        if: ${{ matrix.wagtail-version != 'main' }}
        run: |
          pip install wagtail==${{ matrix.wagtail-version }}

      - name: Install Wagtail main
        if: ${{ matrix.wagtail-version == 'main' }}
        run: |
          git clone https://github.com/wagtail/wagtail.git
          pip install ./wagtail

      - name: Run Tests
        run: |
          cd example
          python manage.py migrate
          python manage.py test

  test_channels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -r requirements-channels.txt
          pip install .

      - name: Run Tests
        run: |
          cd example
          python manage.py migrate
          python manage.py test
